defaults: &defaults
  working_directory: ~
  docker:
  - image: blockmason/lndr-circleci:1.0.1

version: 2
jobs:
  build:
    <<: *defaults
    steps:
    - checkout
    - restore_cache:
        keys:
        - v2-{{ checksum "stack.yaml" }}
    - run:
        name: stack setup
        command: |
          stack setup
    - run:
        name: stack install
        command: |
          stack install
    - save_cache:
        key: v2-{{ checksum "stack.yaml" }}
        paths:
        - ~/.ghc
        - ~/.cabal
        - ~/.stack
    - run:
        name: Prepare artifacts
        command: |
          mkdir artifacts
          cp \
            "${HOME}/.local/bin/lndr-server" \
            "${HOME}/.local/bin/lndr" \
            Dockerfile \
            .dockerignore \
            artifacts/
          for file in $(perl -n -e'/^!\/(.+)/ && print "$1\n"' < .dockerignore | xargs); do
            if [ -f "${file}" ]; then
              mkdir -p "artifacts/$(dirname "${file}")"
              cp "${file}" "artifacts/${file}"
            fi
          done
    - store_artifacts:
        path: artifacts
    - run:
        name: Publishing (only on master if version has changed)
        command: |
          if [ master = "${CIRCLE_BRANCH}" ]; then
            if [ -n "${AWS_ACCESS_KEY_ID}" ]; then
              if [ -n "${AWS_SECRET_ACCESS_KEY}" ]; then
                aws s3 cp --acl public-read artifacts/lndr-server "s3://blockmason-artifacts/@blockmason/lndr/${CIRCLE_SHA1}/lndr-server"
              fi
            fi
          fi
